name: StackSpawner
main: uk.antiperson.stackspawner.StackSpawner
version: 1.1.0
website: https://www.spigotmc.org/resources/stackspawner.62284/
permissions:
  stackspawner.commands:
    description: Access to plugin commands.
commands:
  stackspawner:
    permission: stackspawner.commands
    description: The main command.
    aliases: [ss]